// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as FastGlob from "fast-glob";
import * as Primitive_string from "rescript/lib/es6/Primitive_string.js";

function main() {
  let bindings = FastGlob.default.sync(["./src/**/*.res"], {}).filter(dir => !dir.startsWith("./src/scripts/")).map(dir => {
    let name = dir.replace("./src/", "").split("/").slice(0, -1).join("/");
    let href = dir.slice(2).split("/").slice(0, -1).join("/");
    return {
      name: name,
      href: href
    };
  }).toSorted((a, b) => Primitive_string.compare(a.name, b.name));
  let readmeTemplate = Fs.readFileSync("./templates/README.template", "utf8");
  let readme = readmeTemplate.replace("{{bindings}}", bindings.map(binding => "- [" + binding.name + "](" + binding.href + ")").join("\n"));
  Fs.writeFileSync("./README.md", readme, "utf8");
  console.log("README.md generated with " + bindings.length.toString() + " bindings");
}

main();

export {
  main,
}
/*  Not a pure module */
