// Generated by ReScript, PLEASE EDIT WITH CARE


let AnimateSharedLayout = {};

let AnimatePresence = {};

function makeAnimationConfig(opacity, scale, x, y) {
  return {
    opacity: opacity,
    scale: scale,
    x: x,
    y: y
  };
}

function makeSpringTransitionConfig(damping, stiffness) {
  return {
    type: "spring",
    damping: damping,
    stiffness: stiffness
  };
}

let Div = {};

let Tr = {};

let Img = {};

let Span = {};

let P = {};

let Ul = {};

let Li = {};

let M = {
  Div: Div,
  Tr: Tr,
  Img: Img,
  Span: Span,
  P: P,
  Ul: Ul,
  Li: Li
};

export {
  AnimateSharedLayout,
  AnimatePresence,
  makeAnimationConfig,
  makeSpringTransitionConfig,
  M,
}
/* No side effect */
